apiVersion: apps/v1
kind: Deployment
metadata:
  name: seekersplus-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seekersplus
  template:
    metadata:
      labels:
        app: seekersplus
    spec:
      containers:
      - name: seekersplus
        image: stenny1710/seekersplus:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: seekersplus-service
spec:
  type: LoadBalancer
  selector:
    app: seekersplus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
